_target_: vc_models.models.load_model
model:
  _target_: vc_models.models.vit.dinov3.load_mae_encoder
  checkpoint_path: model_ckpts/dinov3/dinov3_vith16plus_pretrain_lvd1689m-7c1da9a5.pth
  subkey: ""
  model:
    _target_: vc_models.models.vit.dinov3.vit_huge_patch16
    # https://github.com/facebookresearch/dinov3/blob/cb054165e9ec6bd86dbae674416eb36c8349adcb/dinov3/hub/backbones.py#L413-L449
    layerscale_init: 1e-5
    n_storage_tokens: 4
    pos_embed_rope_rescale_coords: 2
    pos_embed_rope_dtype: "fp32"
    norm_layer: "layernormbf16"
    ffn_bias: true
    proj_bias: true
    mask_k_bias: true
    embed_dim: 1280
    use_cls: false
    global_pool: True
    ffn_ratio: 6.0
    qkv_bias: true
    drop_path_rate: 0.0
    ffn_layer: "swiglu"
    compact_arch_name: "vithplus"
transform:
  _target_: vc_models.transforms.vit_transforms
metadata:
  algo: mae
  model: vit_huge_patch16_dinov3
  data:
    - ego
    - imagenet
    - inav
  comment: 182_epochs
