_target_: vc_models.models.load_model
model:
  _target_: vc_models.models.vit.vit.load_mae_encoder
  checkpoint_path: model_ckpts/dinov2/vit_large_patch14_dinov2.lvd142m.bin
  subkey: ""
  model:
    _target_: vc_models.models.vit.vit.vit_large_patch14
    use_cls: True
    drop_path_rate: 0.0
    init_values: 1e-5
    flatten_embedding: True
    embed_dim: 1024
transform:
  _target_: vc_models.transforms.vit_transforms
metadata:
  algo: mae
  model: vit_large_patch14_dinov2
  data:
    - ego
    - imagenet
    - inav
  comment: 182_epochs
