_target_: vc_models.models.load_model
model:
  _target_: vc_models.models.vit.pixo.pixo.load_mae_encoder
  checkpoint_path: model_ckpts/pixo/distill_mask50_grid2_vit_1b_to_huge_cls_l1_patch_l1_avg_teanormFalse_mc2b_hist_area17_x4_bs8192_blr5e-6_ep400.pth
  subkey: "model"
  model:
    _target_: vc_models.models.vit.pixo.pixo.mae_huge
    use_cls: True
    reg_tokens: 3
    avg_cls_reg: True
transform:
  _target_: vc_models.transforms.vit_transforms
metadata:
  algo: mae
  model: vit_huge_patch14_pixo
  data:
    - ego
    - imagenet
    - inav
  comment: 182_epochs
