python bc_experiments/train_bc.py --config-name bc_default.yaml  --multirun hydra/launcher=submitit_slurm     hydra.launcher.account=data hydra.launcher.qos=data_high hydra.launcher.cpus_per_task=10 hydra.launcher.gpus_per_task=1 hydra.launcher.mem_gb=64 hydra.launcher.timeout_min=3600 algo.freeze_pretrained_rep=true rep_to_policy=none task=reach_cube task.n_outer_iter=100 no_wandb=True run_name=reach_cube_test task.n_epoch_every_log=5      seed=100,200,300 algo.pretrained_rep=vc1_vitl,clip_vitb,pixo_vith,r3m,theia_vitb,dinov2_vitl,dinov3_vitl,dinov3_vith,pixo_vith16,pixo_vith_avg_cls_reg

python bc_experiments/train_bc.py --config-name bc_default.yaml  --multirun hydra/launcher=submitit_slurm     hydra.launcher.account=data hydra.launcher.qos=data_high hydra.launcher.cpus_per_task=10 hydra.launcher.gpus_per_task=1 hydra.launcher.mem_gb=64 hydra.launcher.timeout_min=3600 algo.freeze_pretrained_rep=true rep_to_policy=none task=move_cube task.n_outer_iter=1000 no_wandb=True run_name=move_cube_test task.n_epoch_every_log=50      seed=100,200,300 algo.pretrained_rep=vc1_vitl,clip_vitb,pixo_vith,r3m,theia_vitb,dinov2_vitl,dinov3_vitl,dinov3_vith,pixo_vith16,pixo_vith_avg_cls_reg


# next is run spatial

python bc_experiments/train_bc.py --config-name bc_default.yaml  --multirun hydra/launcher=submitit_slurm     hydra.launcher.account=data hydra.launcher.qos=data_high hydra.launcher.cpus_per_task=10 hydra.launcher.gpus_per_task=1 hydra.launcher.mem_gb=64 hydra.launcher.timeout_min=3600 algo.freeze_pretrained_rep=true rep_to_policy=none task=reach_cube task.n_outer_iter=100 no_wandb=True run_name=reach_cube_test task.n_epoch_every_log=5      seed=100,200,300 algo.pretrained_rep=vc1_vitl_sp,pixo_vith_sp,theia_vitb_sp,dinov2_vitl_sp,dinov3_vitl_sp,dinov3_vith_sp,pixo_vith16_sp

python bc_experiments/train_bc.py --config-name bc_default.yaml  --multirun hydra/launcher=submitit_slurm     hydra.launcher.account=data hydra.launcher.qos=data_high hydra.launcher.cpus_per_task=10 hydra.launcher.gpus_per_task=1 hydra.launcher.mem_gb=64 hydra.launcher.timeout_min=3600 algo.freeze_pretrained_rep=true rep_to_policy=none task=move_cube task.n_outer_iter=1000 no_wandb=True run_name=move_cube_test task.n_epoch_every_log=50      seed=100,200,300 algo.pretrained_rep=vc1_vitl_sp,pixo_vith_sp,theia_vitb_sp,dinov2_vitl_sp,dinov3_vitl_sp,dinov3_vith_sp,pixo_vith16_sp
